# Default configuration file for obsidian2perplexity

[routing]
# The API endpoint for Perplexity's chat completions.
PERPLEXITY_API_URL = "https://api.perplexity.ai/chat/completions"

# Specifies the origins allowed for CORS requests, ensuring compatibility between Obsidian and Perplexity.
ALLOWED_ORIGINS = "app://obsidian.md"

[server]
# The host address the server will bind to. Use "0.0.0.0" to listen on all interfaces.
HOST = "0.0.0.0"
# The port number the server will listen on.
PORT = 8787
# Path to SSL certificate file (PEM format) for HTTPS support.
# SSL_CERTFILE = "/path/to/fullchain.pem"
# Path to SSL private key file (PEM format) for HTTPS support.
# SSL_KEYFILE = "/path/to/privkey.pem"