# Default configuration file for obsidian-ai-bridge

[routing]
# API endpoints for different AI services
PERPLEXITY_API_URL = "https://api.perplexity.ai/chat/completions"
# {model} will be replaced with actual model name from request
GEMINI_EMBEDDING_API_URL = "https://generativelanguage.googleapis.com/v1/models/{model}:embedText"

# Specifies the origins allowed for CORS requests, ensuring compatibility between Obsidian and different AI services.
ALLOWED_ORIGINS = "app://obsidian.md"

[server]
# The host address the server will bind to. Use "0.0.0.0" to listen on all interfaces.
HOST = "0.0.0.0"
# The port number the server will listen on.
PORT = 8787
# Path to SSL certificate file (PEM format) for HTTPS support.
# SSL_CERTFILE = "/path/to/fullchain.pem"
# Path to SSL private key file (PEM format) for HTTPS support.
# SSL_KEYFILE = "/path/to/privkey.pem"