services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: sleep infinity # контейнер живёт, uvicorn/debugpy запускается вручную из VS Code или терминала
